travis:
  secure:
    BINSTAR_TOKEN: Jr1ybDnH5+r1+AuMN7ah5mHUn1C1F/luefLm95vW1InR1JHtRqB8flRNwEx5WOs1y7hfkriGdBEXOJUOteDwgs/tzsoBRyzLztHVKEWRWvL62YZny7y7rN9jWoqL7e2GFa5wWSH9pKQqEIFx0bqvlJkl32slwRqwZpib2/z3xEzg4TN1AlWweZ/CiD+yrYaAR/P4XtGqESZat5A6YcBhqW5fCP18a6+2e7H61R4xWtUbmNIdGEMv93G8L4PtUXJ3qeSxWpFQ1o2Z8ugHpBdW72plRIdKxmbHaZnlinQ61ZWeWn5e2jdfJLGg7+EFjbs/D765BpDCEel2i/60n5SuWPvuXN7k+O5/KIwhy/zssY75fuO/l+7SnYkVOj4mZZcEa9z4x8aaMqAcEoX7HohEW1XtfuuQkFA3xgS+auxxAxjKIfi8QZqLSesKRkbKtZ//L0PONlulhHgFWvapRPpcTeyEiBnOk2ER9bxbZ+VQA3HpvCEgCgROXunwH9VkcPwUqas9t0uco5+tKyrq3WYhV054p6FrConm5UNqyACXaSHsUb4su7kxviQLotcFgQdCwt7SIyIedQqHfSV+Gp47wUUBk7ZudZKUoCqwLkneucEFenO5xnIu7ff1dCHjwFNEIF3oMxnz0ctgIcj4P6omlEFfHbbPO4/7Cm8IU/rE00s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
